# Generated by Django 3.1.6 on 2021-02-07 03:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='GameScript',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('version', models.IntegerField(default=1)),
            ],
            options={
                'unique_together': {('title', 'version')},
            },
        ),
        migrations.CreateModel(
            name='TokenizedSentence',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Utterance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('speaker', models.CharField(max_length=50)),
                ('utteranceType', models.CharField(choices=[('sp', 'Speaker'), ('co', 'Context'), ('ch', 'Choice')], max_length=2)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gamecorpus.event')),
            ],
        ),
        migrations.CreateModel(
            name='TokenizedWord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=20)),
                ('pos', models.CharField(choices=[('形容詞', 'Adj'), ('助詞', 'Adp'), ('形状詞', 'Adn'), ('副詞', 'Adv'), ('助動詞', 'Aux'), ('接続詞', 'Conj'), ('連体詞', 'Det'), ('感動詞', 'Intj'), ('名詞', 'Noun'), ('接頭辞', 'Prefix'), ('代名詞', 'Prp'), ('補助記号', 'Punct'), ('空白', 'Space'), ('接尾辞', 'Suffix'), ('記号', 'Sym'), ('動詞', 'Verb')], max_length=4)),
                ('lemma', models.CharField(max_length=20)),
            ],
            options={
                'unique_together': {('text', 'pos', 'lemma')},
            },
        ),
        migrations.CreateModel(
            name='TokenizedSentenceWord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sentence', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gamecorpus.tokenizedsentence')),
                ('word', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gamecorpus.tokenizedword')),
            ],
        ),
        migrations.AddField(
            model_name='tokenizedsentence',
            name='utterance',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gamecorpus.utterance'),
        ),
        migrations.CreateModel(
            name='Sentence',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=200)),
                ('utterance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gamecorpus.utterance')),
            ],
        ),
        migrations.CreateModel(
            name='Partition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fileName', models.CharField(max_length=100)),
                ('script', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gamecorpus.gamescript')),
            ],
            options={
                'unique_together': {('fileName', 'script')},
            },
        ),
        migrations.AddField(
            model_name='event',
            name='partition',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gamecorpus.partition'),
        ),
    ]
