# Generated by Django 3.1.6 on 2021-03-07 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gamecorpus', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='gamescript',
            name='comment',
            field=models.CharField(default='', max_length=300),
        ),
        migrations.AddField(
            model_name='gamescript',
            name='isPlayed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='gamescript',
            name='numSentences',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='gamescript',
            name='numWords',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='gamescript',
            name='sourceAttributionUrl',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='partition',
            name='numSentences',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='partition',
            name='numWords',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='partition',
            name='title',
            field=models.CharField(default='', max_length=100),
        ),
    ]
